### ISSUE TITLE
update_dependencies.sh broken due to usage of deprecated command line args

### ISSUE THREAD

**Issue by aagdere** [bazeltools/bazel-deps#325]
Commit https://github.com/bazeltools/bazel-deps/commit/e589b9ac4b0c8ca312d735a6cb51ff62780529a9 got rid of a bunch of command line args like `sha-file`, `target-file`, `disable-3rdparty-in-repo`, etc. This is breaking the newest `update_dependencies.sh` script since it still uses some those.

The README also still contains example usage using them: 
```
cd $BAZEL_DEPS
bazel run //:parse generate -- --repo-root "$MY_PROJ_DIR" --sha-file 3rdparty/workspace.bzl --deps dependencies.yaml --target-file 3rdparty/target_file.bzl --disable-3rdparty-in-repo
```

**Comment by johnynek** [comment]
That was not intended.

Would be happy to add them back.

Also we should add a test to exercise them.

Would you be able to send a PR?

**Comment by lakshmansai** [comment]
I would like to work on this

**Comment by johnynek** [comment]
I believe #327 and #329 fix this. Please reopen if you have any issues.

**Comment by aagdere** [comment]
Apologies for the delayed response, I would have gladly made a PR if I had seen this sooner. I have confirmed the fixes worked for me. Thank you @johnynek and @lakshmansai!
