### ISSUE TITLE
scala 3 support

### ISSUE THREAD

**Issue by pshemass** [bazeltools/bazel-deps#326]
scala_rule has support for scala 3. do you plan to add it too?

**Comment by johnynek** [comment]
Yes it shouldn't be too much work.

**Comment by kmate-ct** [comment]
Are there any progress / plans around this?

**Comment by johnynek** [comment]
This should work.

It was implemented by #356

Please reopen if it doesn't work.

**Comment by kmate-ct** [comment]
Oh, ok, thanks!
