### ISSUE TITLE
bazel-deps does not generate workspace.bzl and BUILD

### ISSUE THREAD

**Issue by grepwood** [bazeltools/bazel-deps#386]
The project I maintain at work uses https://github.com/typedb/bazel-deps/releases/tag/0.3 for reasons lost to time. As that fork is long abandoned I would like to swap it out for the official, original `bazel-deps` as it seems to be well maintained.

First thing I wanted to to is the regenerate the workspace.bzl file because from what I see, typedb's fork makes very different target names for Bazel.

Problem is, when I try to generate the workspace.bzl file with this version, nothing ever happens. In fact if I try to regenerate to overwrite an existing file, it will vanish along with the BUILD file neighbouring it. But the other BUILD files, for all the dependencies individually, appear without issue.

Here is my directory layout:
```
/home/grepwood/git/nice-project
├── 3rdparty
|   ├── jvm-dependencies.yaml
|   └── jvm/
|       ├── BUILD (gets deleted by bazeltools/bazel-deps, generates)
|       ├── workspace.bzl (gets deleted by bazeltools/bazel-deps, never generates)
|       └── (a lot of directories) (generated by bazeltools/bazel-deps and typedb/bazel-deps)
├── WORKSPACE
└── (other things)
```

Here are my steps retraced in the source directory of my project:
```
# More or less, we use a private mirror
curl -LO https://github.com/bazeltools/bazel-deps/releases/download/v0.1-60/bazel-deps.jar
# Now the main course
java -cp bazel-deps.jar com.github.johnynek.bazel_deps.ParseProject generate -r /home/grepwood/git/nice-project -s 3rdparty/jvm/workspace.bzl -d 3rdparty/jvm-dependencies.yaml
```
It just keeps printing something like this:
```
[io-compute-blocker-2] ERROR MakeDeps - directory 3rdparty/jvm/... expected but missing
[io-compute-blocker-2] ERROR MakeDeps - file 3rdparty/jvm/.../BUILD does not exist.
```
After that it writes:
```
wrote 414 targets
```

But to where is anyone's guess. I tried to remove everything from `3rdparty/jvm` except that directory:
```
rm -rf 3rdparty/jvm/*
```
and then I retried:
```
java -cp bazel-deps.jar com.github.johnynek.bazel_deps.ParseProject generate -r /home/grepwood/git/nice-project -s 3rdparty/jvm/workspace.bzl -d 3rdparty/jvm-dependencies.yaml
```
This made the errors go away. It still prints `wrote 414 targets`, it generates all the targets, but it doesn't generate the `3rdparty/jvm/BUILD` and `3rdparty/jvm/workspace.bzl`.

What am I doing wrong?

**Comment by SeaJaredCode** [comment]
I haven't tried to repro, but it works for us following basically the setup described in the README.

Try putting the workspace.bzl file outside the `jvm` folder (which gets deleted every time). I'd guess (without looking at anything) that it generates `workspace.bzl` before deleting `jvm`, so you see it disappear.

**Comment by grepwood** [comment]
Thank you @SeaJaredCode, I'll try that tomorrow when I'm at work
